// redux/reducers/ordersSlice.js
import { createSlice } from "@reduxjs/toolkit";

// Your initial state for the orders slice
const initialState: never[] = [];

// Create a slice using Redux Toolkit
const ordersSlice = createSlice({
  name: "orders",
  initialState,
  reducers: {
    setOrders: (state, action) => {
      return action.payload; // Set the orders state with the payload data
    },
    // Add more reducers here as needed
  },
});

// Export the reducer and actions generated by Redux Toolkit
export const { setOrders } = ordersSlice.actions;
export default ordersSlice.reducer;
